openapi: 3.0.0
info:
  title: Pait Doc
  version: 0.0.1
servers:
- url: http://127.0.0.1
tags:
- name: test
  description: test api
- name: user
  description: user api
- name: get
  description: ''
- name: post
  description: ''
- name: depend
  description: ''
paths:
  /api/get/{age}:
    head:
      tags:
      - user
      - get
      summary: ''
      description: Test Field
      operationId: HEAD.test_get
      parameters:
      - name: uid
        in: query
        required: true
        description: user id
        schema:
          title: Uid
          description: user id
          exclusiveMinimum: 10
          exclusiveMaximum: 1000
          type: integer
      - name: user_name
        in: query
        required: true
        description: user name
        schema:
          title: User Name
          description: user name
          maxLength: 4
          minLength: 2
          type: string
      - name: email
        in: query
        required: false
        description: user email
        schema:
          title: Email
          description: user email
          default: example@xxx.com
          type: string
      - name: sex
        in: query
        required: false
        description: sex
        schema:
          title: SexEnum
          description: An enumeration.
          enum:
          - man
          - woman
      - name: age
        in: path
        required: true
        description: age
        schema:
          title: Age
          description: age
          type: integer
      responses:
        200:
          description: success response|fail response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/_ResponseUserModel'
                - $ref: '#/components/schemas/ResponseFailModel'
    get:
      tags:
      - user
      - get
      summary: ''
      description: Test Field
      operationId: GET.test_get
      parameters:
      - name: uid
        in: query
        required: true
        description: user id
        schema:
          title: Uid
          description: user id
          exclusiveMinimum: 10
          exclusiveMaximum: 1000
          type: integer
      - name: user_name
        in: query
        required: true
        description: user name
        schema:
          title: User Name
          description: user name
          maxLength: 4
          minLength: 2
          type: string
      - name: email
        in: query
        required: false
        description: user email
        schema:
          title: Email
          description: user email
          default: example@xxx.com
          type: string
      - name: sex
        in: query
        required: false
        description: sex
        schema:
          title: SexEnum
          description: An enumeration.
          enum:
          - man
          - woman
      - name: age
        in: path
        required: true
        description: age
        schema:
          title: Age
          description: age
          type: integer
      responses:
        200:
          description: success response|fail response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/_ResponseUserModel'
                - $ref: '#/components/schemas/ResponseFailModel'
  /api/post:
    post:
      tags:
      - user
      - post
      summary: ''
      description: Test Method:Post Pydantic Model
      operationId: POST.post_route
      parameters:
      - name: requestBody.content.<media-type>
        in: header
        required: true
        description: content-type
        schema:
          title: Content-Type
          description: content-type
          type: string
      responses:
        200:
          description: success response|fail response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ResponseUserModel'
                - $ref: '#/components/schemas/ResponseFailModel'
      requestBody:
        content:
          application/json:
            schema:
              title: DynamicModel
              type: object
              properties:
                uid:
                  title: Uid
                  type: integer
                user_name:
                  title: User Name
                  type: string
                age:
                  title: Age
                  type: integer
              required:
              - uid
              - user_name
              - age
  /api/depend:
    post:
      tags:
      - user
      - depend
      summary: ''
      description: Test Method:Post request, Pydantic Model
      operationId: POST.test_depend
      parameters:
      - name: uid
        in: query
        required: true
        description: user id
        schema:
          title: Uid
          description: user id
          exclusiveMinimum: 10
          exclusiveMaximum: 1000
          type: integer
      - name: user_name
        in: query
        required: true
        description: user name
        schema:
          title: User Name
          description: user name
          maxLength: 4
          minLength: 2
          type: string
      - name: user-agent
        in: header
        required: true
        description: user agent
        schema:
          title: User-Agent
          description: user agent
          type: string
      responses:
        200:
          description: success response|fail response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ResponseUserModel'
                - $ref: '#/components/schemas/ResponseFailModel'
      requestBody:
        content:
          application/json:
            schema:
              title: DynamicModel
              type: object
              properties:
                age:
                  title: Age
                  description: age
                  exclusiveMinimum: 1
                  exclusiveMaximum: 100
                  type: integer
              required:
              - age
  /api/other_field:
    post:
      tags:
      - user
      - get
      summary: ''
      description: ''
      operationId: POST.other_field_route
      parameters:
      - name: cookie
        in: cookie
        required: true
        description: cookie
        schema:
          title: Cookie
          description: cookie
          type: object
      responses: {}
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              title: DynamicModel
              type: object
              properties:
                a:
                  title: A
                  description: form data
                b:
                  title: B
                  description: form data
  /api/cbv:
    get:
      tags:
      - user
      - get
      summary: ''
      description: Text Pydantic Model and Field
      operationId: get.TestCbv.get
      parameters:
      - name: age
        in: query
        required: true
        description: age
        schema:
          title: Age
          description: age
          exclusiveMinimum: 1
          exclusiveMaximum: 100
          type: integer
      - name: uid
        in: query
        required: true
        description: user id
        schema:
          title: Uid
          description: user id
          exclusiveMinimum: 10
          exclusiveMaximum: 1000
          type: integer
      - name: user_name
        in: query
        required: true
        description: user name
        schema:
          title: User Name
          description: user name
          maxLength: 4
          minLength: 2
          type: string
      - name: email
        in: query
        required: false
        description: user email
        schema:
          title: Email
          description: user email
          default: example@xxx.com
          type: string
      - name: user-agent
        in: header
        required: true
        description: ua
        schema:
          title: User-Agent
          description: ua
          type: string
      responses:
        200:
          description: success response|fail response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/_ResponseUserModel'
                - $ref: '#/components/schemas/ResponseFailModel'
    post:
      tags:
      - user
      - post
      summary: ''
      description: test cbv post method
      operationId: post.TestCbv.post
      parameters:
      - name: user-agent
        in: header
        required: true
        description: ua
        schema:
          title: User-Agent
          description: ua
          type: string
      responses:
        200:
          description: success response|fail response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ResponseUserModel'
                - $ref: '#/components/schemas/ResponseFailModel'
      requestBody:
        content:
          application/json:
            schema:
              title: DynamicModel
              type: object
              properties:
                uid:
                  title: Uid
                  type: integer
                user_name:
                  title: User Name
                  type: string
                age:
                  title: Age
                  type: integer
              required:
              - uid
              - user_name
              - age
  /api/raise_tip:
    post:
      tags:
      - test
      deprecated: true
      summary: ''
      description: test pait raise tip
      operationId: POST.raise_tip_route
      parameters:
      - name: content_type
        in: header
        required: true
        description: content-type
        schema:
          title: Content Type
          description: content-type
          type: string
      responses:
        200:
          description: success response|fail response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ResponseUserModel'
                - $ref: '#/components/schemas/ResponseFailModel'
      requestBody:
        content:
          application/json:
            schema:
              title: DynamicModel
              type: object
              properties:
                uid:
                  title: Uid
                  type: integer
                user_name:
                  title: User Name
                  type: string
                age:
                  title: Age
                  type: integer
              required:
              - uid
              - user_name
              - age
  /api/pait_model:
    post:
      tags:
      - test
      summary: ''
      description: Test Field
      operationId: POST.test_pait_model
      parameters:
      - name: uid
        in: query
        required: true
        description: user id
        schema:
          title: Uid
          description: user id
          exclusiveMinimum: 10
          exclusiveMaximum: 1000
          type: integer
      - name: user_name
        in: query
        required: true
        description: user name
        schema:
          title: User Name
          description: user name
          maxLength: 4
          minLength: 2
          type: string
      - name: user-agent
        in: header
        required: true
        description: user agent
        schema:
          title: User-Agent
          description: user agent
          type: string
      responses:
        200:
          description: success response|fail response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ResponseUserModel'
                - $ref: '#/components/schemas/ResponseFailModel'
      requestBody:
        content:
          application/json:
            schema:
              title: DynamicModel
              type: object
              properties:
                age:
                  title: Age
                  description: age
                  exclusiveMinimum: 1
                  exclusiveMaximum: 100
                  type: integer
              required:
              - age
components:
  schemas:
    _BaseModel:
      title: _BaseModel
      type: object
      properties:
        uid:
          title: Uid
          description: user id
          exclusiveMinimum: 10
          exclusiveMaximum: 1000
          type: integer
        user_name:
          title: User Name
          description: user name
          maxLength: 4
          minLength: 2
          type: string
        age:
          title: Age
          description: age
          exclusiveMinimum: 1
          exclusiveMaximum: 100
          type: integer
        content_type:
          title: Content Type
          description: content-type
          type: string
      required:
      - uid
      - user_name
      - age
      - content_type
    _ResponseUserModel:
      title: _ResponseUserModel
      type: object
      properties:
        code:
          title: Code
          description: api code
          default: 0
          type: integer
        msg:
          title: Msg
          description: api status msg
          default: success
          type: string
        data:
          $ref: '#/components/schemas/_BaseModel'
      required:
      - data
    ResponseFailModel:
      title: ResponseFailModel
      type: object
      properties:
        code:
          title: Code
          description: api code
          default: 1
          type: integer
        msg:
          title: Msg
          description: api status msg
          default: fail
          type: string
    ResponseUserModel:
      title: ResponseUserModel
      type: object
      properties:
        code:
          title: Code
          description: api code
          default: 0
          type: integer
        msg:
          title: Msg
          description: api status msg
          default: success
          type: string
        data:
          title: Data
          type: array
          items:
            $ref: '#/components/schemas/_BaseModel'
      required:
      - data
